name: CI-iOS

on:
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build-and-test"
  build-and-test:
    # The type of runner that the job will run on
    runs-on: macos-13

    timeout-minutes: 10

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_14.3.app
      
    - name: Xcode version
      run: /usr/bin/xcodebuild -version
      
    - name: Install Dependencies
      run: |
        brew install swiftlint
      
    - name: Build and Test
      run: |
        xcodebuild clean build test -project EssentialFeed.xcodeproj -scheme "CI_iOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 14,OS=16.4" ONLY_ACTIVE_ARCH=YES

#    - name: Lint Swift Code
#      run: |
#        swiftlint lint
